
development:
  adapter: mysql2
  database: hslog_development
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: hslog_test
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: hslog_base
  pool: 5
  timeout: 5000
